[package]
name = "rust-xube"
version = "0.1.0"
authors = ["ewgenius <ewgeniux@gmail.com>"]

[dependencies]
piston = "0.16.0"
piston2d-graphics = "0.13.0"
pistoncore-glutin_window = "0.20.0"
piston2d-opengl_graphics = "0.22.0"
